### ISSUE TITLE
[Epic] Governing the Information Age: Reboot - P2016

### ISSUE THREAD

**Issue by theo-cox** [open-revolution/research#2]
See [A10 ](https://docs.google.com/document/d/1USSez4_suV3FqXuG6HY0uwLRMhSKbb6gX9Sytg6FGig/edit#heading=h.599vpyhb8naq)for project outline and background

[Project folder](https://drive.google.com/drive/folders/1N4TBeoFgOKHQCaeugwJO_YTGOA2L0k3z?usp=sharing)

## Acceptance

- [ ] Core, existing content published and promoted
- [ ] Website updated to integrate this workstream, contextualise it in our wider work, and publicise a consultancy offering
- [ ] Theo has enough expertise and recognition to independently lead project delivery and BizDev around information governance/remuneration rights (even if Rufus remains figurehead for things like proposals)

## Tasks

- [x] Launch blog for GIZ **Done: https://lifeitself.us/2021/12/14/life-itself-providing-expert-support-on-environmental-data-sharing-incentives/**
- [ ] @rufuspollock  to make a preliminary pass of Open Rev to identify low hanging fruit
- [ ] @theo-cox and @rufuspollock to review existing Open Revolution content
- [ ] Create a plan of work for content publishing (and upskilling more broadly?)
- [ ] Publish core work
- [ ] Promote publications
- [ ] Create plan of work for grant and consultancy seeking
- [ ] ...

**Comment by theo-cox** [comment]
@rufuspollock as per Friday's actions see here for epic and linked A10 for rebooting Open Rev type stuff

**Comment by rufuspollock** [comment]
@theo-cox great

Meta question: i'm wondering where we track this stuff - i was hoping to keep "research" clean and do everything in a public repo e.g. openrevolution.net (i don't want to get myself lost in too may repos). I feel this stuff is almost more life itself'y so should go in e.g. labs for now IMO. Could we copy it across there for now? (you can't transfer issues between orgs ...)

**Comment by theo-cox** [comment]
@rufuspollock closing as have moved to https://github.com/life-itself/labs/issues/47.
